# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Jonathan's Notes
tagline:             'Notes from a procrastinating part-time coder/hacker/maker'
description:         'Random musings about probably half-finished projects.'
url:                 http://jmb.github.io
baseurl:             ''
paginate:            5
gems: ["jekyll-paginate"]

# About/contact
author:
  name:              Jonathan Batchelor
  url:               https://twitter.com/jmbatchelor
#  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
